version: '3.1'

services:
  app:
    build: .
    command: bash -c "python /app/manage.py collectstatic -v0 --noinput && python /app/manage.py migrate --noinput && cd /app && gunicorn config.wsgi --bind=0.0.0.0:8000 --workers=3"
    stdin_open: true
    tty: true
    restart: always
    environment:
      DJANGO_SETTINGS_MODULE: '${DJANGO_SETTINGS_MODULE}'
      RABBITMQ_URL: '${RABBITMQ_URL}'
    volumes:
      - ./app:/app
      - ./public:/public
    depends_on:
      - postgres

  postgres:
    build:
      ./postgres
    restart: always
    environment:
      DATABASE_NAME: '${DATABASE_NAME}'
      DATABASE_USER: '${DATABASE_USER}'
      DATABASE_PASSWORD: '${DATABASE_PASSWORD}'
    volumes:
      - ./dockerfiles/pgdata:/var/lib/postgresql/data

  nginx:
    build:
      ./nginx
    restart: always
    env_file:
      - ./nginx/.env
    ports:
      - "${NGINX_OUT_PORT}:80"
    volumes:
      - ./public:/public
