# Generated by Django 2.0 on 2019-09-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0002_moderatedtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_level', models.CharField(max_length=15)),
                ('task_description', models.CharField(max_length=255)),
            ],
        ),
    ]
