# Generated by Django 2.0 on 2019-09-18 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0004_auto_20190917_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mine.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.TextField(),
        ),
    ]
