# Generated by Django 2.0 on 2019-10-02 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mine', '0008_auto_20191001_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='participant',
            field=models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
