# Generated by Django 2.0 on 2019-10-02 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0009_classroom_participant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='participant',
            new_name='participants',
        ),
    ]
