# Generated by Django 2.0 on 2019-10-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0010_auto_20191002_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroompeople',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='classroompeople',
            name='user',
        ),
        migrations.RemoveField(
            model_name='classroomtask',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='classroomtask',
            name='task',
        ),
        migrations.AddField(
            model_name='classroom',
            name='tasks',
            field=models.ManyToManyField(to='mine.Task'),
        ),
        migrations.DeleteModel(
            name='ClassroomPeople',
        ),
        migrations.DeleteModel(
            name='ClassroomTask',
        ),
    ]
