# Generated by Django 2.0 on 2019-10-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0011_auto_20191002_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='tasks',
            field=models.ManyToManyField(null=True, to='mine.Task'),
        ),
    ]
