# Generated by Django 2.0 on 2019-10-02 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0013_auto_20191002_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
