# Generated by Django 2.0 on 2019-10-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0014_auto_20191002_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
