# Generated by Django 2.0 on 2019-10-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0015_auto_20191003_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='invitation_code',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
