# Generated by Django 2.0 on 2019-10-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0016_classroom_invitation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='invitation_code',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
