# Generated by Django 2.0 on 2019-10-04 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0019_auto_20191005_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='mine.Classroom'),
        ),
    ]
