# Generated by Django 2.0 on 2019-10-07 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0021_text_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_tasks', to='mine.Classroom'),
        ),
    ]
