# Generated by Django 2.0 on 2019-10-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0026_auto_20191010_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miner',
            name='classroom',
            field=models.ManyToManyField(blank=True, related_name='participant', to='mine.Classroom'),
        ),
    ]
