# Generated by Django 2.0 on 2019-10-10 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0027_auto_20191010_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='participants',
        ),
    ]
