# Generated by Django 2.0 on 2019-10-11 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0030_remove_text_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_tasks', to='mine.Miner'),
        ),
    ]
