# Generated by Django 2.0 on 2019-10-11 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0031_auto_20191011_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_tasks', to='mine.Classroom'),
        ),
    ]
