# Generated by Django 2.0 on 2019-11-06 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0038_auto_20191024_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_level',
            field=models.CharField(choices=[('BEGINNER', 'Жеңіл деңгей'), ('INTERMEDIATE', 'Орташа деңгей'), ('ADVANCED', 'Күрделі деңгей')], default='BEGINNER', max_length=12),
        ),
    ]
