# Generated by Django 2.0 on 2019-11-06 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0039_auto_20191106_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatedtext',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='text',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
